### ISSUE TITLE
生成的好几个视频在左侧会有出现诡异的竖杠大线条，这是为什么？

### ISSUE THREAD

**Issue by lemon360** [IamCreateAI/Ruyi-Models#1]
https://github.com/user-attachments/assets/3da61ad2-976b-4f81-864b-683f85b64af6

生成的好几个视频在左侧会有出现诡异的竖杠大线条，这是为什么？

**Comment by cellzero** [comment]
这可能模型发布前，最后一批高质量数据 finetune 缺少这个比例的视频导致的。使用 横向图片 或 纵向较长的图片（如 9:16、9:21等）较不容易出现此情况。目前我们正在积极排查、修复，待测试稳定后会在 huggingface 上更新模型。更新后，将在本 Issue 中更新进度，随后再关闭 Issue。

**Comment by cellzero** [comment]
这可能模型发布前，最后一批高质量数据 finetune 缺少这个比例的视频导致的。使用 横向图片 或 纵向较长的图片（如 9:16、9:21等）较不容易出现此情况。目前我们正在积极排查、修复，待测试稳定后会在 huggingface 上更新模型。更新后，将在本 Issue 中更新进度，随后再关闭 Issue。

**Comment by lemon360** [comment]
> 这可能模型发布前，最后一批高质量数据 finetune 缺少这个比例的视频导致的。使用 横向图片 或 纵向较长的图片（如 9:16、9:21等）较不容易出现此情况。目前我们正在积极排查、修复，待测试稳定后会在 huggingface 上更新模型。更新后，将在本 Issue 中更新进度，随后再关闭 Issue。
> 
> This may be caused by the lack of videos of this ratio in the last batch of high-quality data finetuning before the model was released. This situation is less likely to occur when using horizontal images or vertically longer images (such as 9:16, 9:21, etc.). We are currently actively investigating and fixing it, and will update the model on huggingface after the test is stable. After the update, the progress will be updated in this issue, and then the issue will be closed.

试了一下，1:1比例的图片不会出现这个问题

**Comment by cellzero** [comment]
嗯嗯，目前主要是 3:4 、4:5 等比例容易出现问题，其他比例大概率是 OK 的。

Yes, at present, problems are mainly caused by ratios such as 3:4 and 4:5, and other ratios are most likely OK.

**Comment by happynear** [comment]
你好，Ruyi模型已经更新，请再尝试一下。
Hi，we update a new version of ruyi. Now the problem should be solved. Please try again.
This issue will be closed.
