### ISSUE TITLE
3090 Speed

### ISSUE THREAD

**Issue by bmgjet** [IamCreateAI/Ruyi-Models#14]
Im just trying to understand the speed chart and if I'm getting about what I should expect for a 3090.
A 4090 would be getting 01:18s. Im Guessing that means 1min 18sec where Im getting 1min 35sec so 82.11% of the same performance.
![ruyi-3090-test1](https://github.com/user-attachments/assets/cae70924-831c-4df4-a357-fc6617f6f21d)

While at 768 Im getting 4min 39 sec compared to the 4090s so 56.63% of the same performance.
![ruyi-3090-test2](https://github.com/user-attachments/assets/84a1848b-bf56-4b9b-bc90-1896e19345e3)

**Comment by cellzero** [comment]
Great job on the Ruyi-GUI! Well done!

Regarding execution speed, the screenshots do show a significant discrepancy, which confuses me a bit.

There could be many factors affecting execution speed, and I suspect it may be related to the GPU's cache size. For instance, when generating 768 resolution videos, the GPU cache required by the RTX 3090 for calculating Attention might exceed the requirements for using **FlashAttention in Torch's scaled_dot_product_attention**. As a result, this optimization method **may not have been utilized**, leading to slower computation speeds.

If possible, could you check whether FlashAttention was enabled on the RTX 3090 when generating 768 resolution videos?

**Comment by bmgjet** [comment]
You are correct. Looking in the log I can see 
"UserWarning: 1Torch was not compiled with flash attention."
Iv looked for a package for windows 11 that has it compiled but there doesn't seem to be any available and trying to compile it myself ends up in a dependency loop. Altho even with that warning iv managed to run 512, 120 frames  normal mode 0 steps where the 4090 chart says --- for OOM. It does take a hour tho lol.

I tried some other environment builds and so far CU12.4 and Torch24 give the best performance. For 768 resolution 11.56% better.
![3090](https://github.com/user-attachments/assets/91509fa1-42de-4f4b-8289-8f65f385dc84)

I made a github repo for the GUI https://github.com/bmgjet/Ruyi-GUI
Altho I wont be making any more changes to it since main reason I wanted it was so I could make a queue of a few jobs to run over night while I wasn't on the computer and it serves it purpose for that.

**Comment by cellzero** [comment]
Yes, the running environment is indeed very complex, especially when it comes to compilation or acceleration. In different running environments, I often notice variations in execution time and memory peaks, but I can't always find the reasons. Therefore, charts may really only serve as references, lol.

At the same time, thank you for creating [Ruyi-GUI](https://github.com/bmgjet/Ruyi-GUI); I think it's a fantastic project. I will ask my teammates if we can add a community support section in the README and include Ruyi-GUI in it. Of course, all of this would require your approval.

**Comment by bmgjet** [comment]
You can use Ryui-GUI how ever you want. The code is not the nicest since Iv only spent an hour and a bit on it.

Maybe a more easier to understand performance metric would be s/it and memory use.
I just finished a run at "512 resolution, 120 frames, normal +7" that ran at 38.26s/it using 23195mb taking 15min 57sec.
So 55.39% the performance of the 4090 in the chart.

If you want me to run the most popular settings to build performance expectation chart I can.
Looking at the spec difference of the 3090 and 4090 I'm probably getting what I should be even with "1Torch was not compiled with flash attention" warning. Since with the big clock speed advantage and a lot more cores on the 4090 it should be about twice the speed of a 3090.

**Comment by cellzero** [comment]
Yes, we are indeed missing data for the RTX 3090. If you could help us improve the performance expectation chart, that would be fantastic! Thank you very much for your assistance.

We use minutes as the unit in our tables because the "s/it" metric only reflects the processing time of the Transformer, while the model requires additional time to execute the VAE. Depending on the video resolution and frame rate, this can add anywhere from several seconds to a few minutes of processing time. 

Of course, using "s/it" as a reference can still provide a rough estimate of the expected time, and I believe that’s perfectly acceptable as well.

**Comment by bmgjet** [comment]
I don't know how much the other hardware in the computer also effects the performance but I queued up the what Id consider the best settings to use since I don't have the time to run every setting thats listed in the chart.
Also not sure how comparable the times would be since I used a timer my GUI that times between starting the command and the .mp4 file being saved and it averaged the s/it reported. So I could just pull the info from the log.txt.

Looking at the time vs s/it they do seem very close other then at 768 res 120 frames which I suspect the timer was also getting locked up when windows UI was locking up as it swapped vram into system ram.

Here is what I have.
CPU 7950X
Ram 64GB 6200mhz, 30,32,32
NVME 990 Pro
3090 (Water Cooled 500W PL, +1000mhz Vram) Sits about 2.1ghz on core.

Memory usage reported from GPUz logs.
Torch was not compiled with flash attention
Windows 11 Using Python Environment from Forge (webui_forge_cu124_torch24.7z) Feb 5 2024

512
24 frames,normal 0 - 18117mb 1:32s - 3.80s/it
48 frames,normal 0 - 19995mb 4:06s - 9.98s/it
72 frames,normal 0 - 22133mb 9:57s - 23.88s/it
96 frames,normal 10 - 22200mb  12:51 - 30.84s/it
120 frames,normal 7 - 23195mb  15:57 - 38.26s/it

768
24 frames,normal 0 - 22105mb 4:07s - 9.94s/it
48 frames,normal 7 - 22195mb 14:34s - 34.98s/it
72 frames,lowmem 0 - 17998mb 38:29s - 91.99s/it
96 frames,lowmem 0 - 23000mb 1:04:16s - 153.74s/it
120 frames,lowmem 0 - 28195mb 5:29:54s - 797.28s/it (froze system during vram overflows for a few sec each pass)

**Comment by cellzero** [comment]
Thank you for your assistance ~

I think this method of calculating time is reasonable. Initially, I misunderstood that the s/it value was derived from the tqdm progress bar output in the predict_i2v.py script, which only accounts for the time taken by the transformer, and is therefore usually smaller.

I have updated your results on the GitHub page, which can be viewed at [gpu_memory_appendix.md](https://github.com/IamCreateAI/Ruyi-Models/blob/main/assets/gpu_memory_appendix.md).

**Comment by bmgjet** [comment]
Left it running over night with some 120 frame 768 res settings.
Looks like it doesnt crash going over the max memory of the GPU it just gets way way slower.

So with 120 frames 768 res the fastest setting is.
low_gpu_mode + 10 steps
This has it using 23222mb, 1:25:02s - 207.41s/it
Which is way better then 5:29:54s - 797.28s/it using low_gpu_mode + 0

Ill try. 120 frames 896 res low_gpu_mode + 1 steps next.
Which you have as 55:50s on the 4090. Im going to guess thats going to be 3 hours on a 3090.

**Comment by cellzero** [comment]
Thank you for your testing. I'm glad to see that the execution time has been reduced for 768 resolution and 120 frames.

I will update the results after testing 120 frames with 896 resolution in low GPU mode and 1 step. I hope it can be done within 2 hours.

**Comment by bmgjet** [comment]
What did you get on your 4090 with that setting,
I just tried 120 frames 896 resolution with low memory mode +1 step.
Took 2:29:45 - 356.01s/it

**Comment by cellzero** [comment]
About 55 minutes, using 120 frames 896 resolution low memory mode +1 step.

Based on that, I initially thought it might take around 2 hours on the 3090. In comparison to the results at 768 resolution (with low memory mode and 10 steps), the 4090 takes about 33 minutes, while the 3090 takes approximately 85 minutes. Therefore, 2 hours and 30 minutes might be a more reasonable estimate.
